# -*- coding: utf-8 -*-
"""ProjetoCompleto_SabrinadaSilva_Imersão Alura

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qO2J2UBwwpOtToBcewobcN0-WKNThVN
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai google-adk

# Configuração da API Key do Google Gemini

import os
from google.colab import userdata
import google.generativeai as genai

# Configuração da API Key do Google Gemini
GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY")
if not GOOGLE_API_KEY:
    print("🚨 Chave da API do Google não encontrada! Configure a GOOGLE_API_KEY no Colab Secrets.")
    # Você pode querer interromper a execução aqui se a chave for crucial
    # exit()
else:
    os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY
    genai.configure(api_key=GOOGLE_API_KEY) # Configura a API key para a biblioteca genai
    print("✅ Chave da API do Google configurada.")

# -*- coding: utf-8 -*-
"""ProjetoCompleto_SabrinadaSilva_Imersão Alura

Geradao Automaticamente por Colab.

Arquivo original localizado em:
    https://colab.research.google.com/drive/12qO2J2UBwwpOtToBcewobcN0-WKNThVN
"""

# Configura o cliente da SDK do Gemini

from google import genai

MODEL_ID = "gemini-2.0-flash"

# Instalar Framework ADK de agentes do Google ################################################
!pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search as google_search_tool_instance # Renomeado para evitar conflito
from google.genai import types  # Para criar conteúdos (Content e Part)
from google.generativeai import GenerativeModel # Importe GenerativeModel diretamente
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown, HTML # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings
import re


warnings.filterwarnings("ignore")

import asyncio

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
async def call_agent(agent: Agent, message_text: str) -> str: # Torne a função assíncrona
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    async for event in runner.run(user_id="user1", session_id="session1", new_message=content): # Use async for e await
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

# %%
#################################################
# --- Agente 1: Engajamento e Boas - Vindas --- #
#################################################

# Tornar esta função assíncrona, pois ela chama await generate_content
async def agente_boas_vindas():
    """Gera a mensagem de boas-vindas formatada para o usuário."""
    prompt_boas_vindas = f"""
    Você é um agente de engajamento e boas-vindas para um chatbot educacional.
    Sua função é iniciar a conversa de forma amigável e explicar o propósito do chatbot,
    definindo expectativas sobre como ele pode ajudar os estudantes do ensino fundamental e médio.

    Use a seguinte formatação Markdown para sua mensagem:

    # Bem-vindo ao Chatbot Educacional Interativo! 👋

    Olá! Sou seu assistente virtual de aprendizado, criado para te ajudar a explorar os conteúdos escolares de uma forma diferente.

    <br>**Meu objetivo principal é te ajudar a:**

    * Construir seu conhecimento de forma ativa e profunda.
    * Desenvolver seu pensamento crítico ao invés de apenas copiar respostas.
    * Explorar os temas através de perguntas desafiadoras e discussões interessantes.
    * Utilizar informações de fontes confiáveis e com referências claras.

    <br>**Como posso te ajudar hoje?**

    Você pode me fazer perguntas sobre os temas que está estudando, pedir explicações ou explorar novos conceitos. Lembre-se, meu foco é te guiar na descoberta do conhecimento, então minhas respostas serão mais como um guia do que uma resposta pronta.

    Para encerrar a conversa a qualquer momento, basta digitar 'sair', 'fim' ou 'adeus'.

    *Vamos começar a aprender juntos! Qual assunto te interessa hoje?*<br>
    """

    print("DEBUG: Agente boas-vindas iniciado.")
    try:
        # Instancia corretamente o GenerativeModel
        # Use await aqui, pois generate_content é assíncrono
        model = GenerativeModel(MODEL_ID) # Use a variável global MODEL_ID
        print(f"DEBUG: Tentando gerar conteúdo com o modelo {MODEL_ID}...")
        response = await model.generate_content(prompt_boas_vindas)
        print("DEBUG: generate_content executado.")

        # Adicionando DEBUG para verificar o conteúdo da resposta
        print(f"DEBUG: Objeto de resposta do modelo: {response}")
        if response and response.candidates and response.candidates[0].content.parts:
             print(f"DEBUG: Partes do conteúdo encontradas.")
             # Acessa o texto da resposta de forma segura
             generated_text = response.text
             print(f"DEBUG: Texto gerado pelo modelo (primeiros 100 chars): {generated_text[:100]}...")
             return generated_text
        else:
             print("DEBUG: Nenhuma parte de conteúdo de texto encontrada na resposta do modelo.")
             return "Não foi possível gerar a mensagem de boas-vindas."

    except ConnectionError as e:
        print(f"DEBUG: Erro de conexão capturado: {e}")
        print(f"Erro de conexão ao tentar acessar a API do Gemini: {e}")
        return "Desculpe, não consegui me conectar ao serviço no momento. Por favor, tente novamente mais tarde."
    except Exception as e: # Captura outros erros inesperados
        print(f"DEBUG: Outro erro capturado: {e}")
        print(f"Ocorreu um erro ao gerar a mensagem de boas-vindas: {e}")
        return "Desculpe, ocorreu um erro interno ao iniciar."

# %%
############################################
# --- Agente 2: Questionamento Guiado  --- #
############################################

from google.adk.agents import Agent

# Tornar esta função assíncrona, pois ela chama await call_agent
async def agente_questionador(pergunta_inicial, historico_conversa=None):
    """
    Agente que recebe uma pergunta do estudante e formula perguntas de acompanhamento
    para guiar o aluno na construção do conhecimento (usando apenas google-adk).

    Args:
        pergunta_inicial (str): A pergunta inicial do estudante.
        historico_conversa (list, optional): Lista de interações anteriores
            (perguntas e respostas) para manter o contexto. Defaults to None.

    Returns:
        str: A pergunta de acompanhamento gerada pelo agente.
    """

    instruction_base = """
    Você é um tutor virtual experiente, focado em ajudar estudantes a aprenderem ativamente.
    Seu objetivo é responder às perguntas dos estudantes não com respostas diretas,
    mas através de perguntas que os incentivem a pensar criticamente e construir seu próprio conhecimento.

    Ao receber uma pergunta, você deve:
    1. Identificar os principais conceitos na pergunta do estudante.
    2. Formular uma ou duas perguntas de acompanhamento que ajudem o estudante a refletir
       sobre esses conceitos, a considerar diferentes perspectivas e a conectar ideias.
    3. Manter o contexto da conversa (se fornecido) para evitar repetições e direcionar o aprendizado.
    4. Priorizar perguntas que estimulem a busca por informações e a análise crítica,
       em vez de simplesmente fornecer respostas.
    5. Seja conciso e claro em suas perguntas.

    Pergunta do estudante: "{pergunta_inicial}"
    """

    # Formatar histórico para a instrução
    historico_str = ""
    if historico_conversa:
        linhas_historico = []
        for item in historico_conversa:
             # Garante que 'role' e 'content' existam e sejam strings antes de formatar
            role = str(item.get('role', 'desconhecido')).capitalize()
            content = str(item.get('content', ''))
            linhas_historico.append(f"{role}: {content}")
        historico_str = "\n".join(linhas_historico)
        instruction = f"{instruction_base}\nHistórico da conversa:\n{historico_str}"
    else:
        instruction = instruction_base


    questionador = Agent(
        name="agente_questionador",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para guiar o aprendizado através de perguntas."
    )

    # A entrada para o agente pode ser apenas a pergunta inicial, o histórico já está na instrução
    # entrada_do_agente = f"Pergunta: {pergunta_inicial}"
    # if historico_conversa:
    #     entrada_do_agente += f"\nHistórico: {historico_conversa}" # Isso duplicaria se já estiver na instrução

    # Passar apenas a pergunta inicial, confiando que a instrução usa o histórico
    entrada_do_agente = pergunta_inicial


    # A interação com o agente (invocando o modelo Gemini) é feita através de 'call_agent'
    # que você já demonstrou usar.
    # Use await aqui, pois call_agent é assíncrono
    pergunta_de_acompanhamento = await call_agent(questionador, entrada_do_agente)
    return pergunta_de_acompanhamento

# %%
####################################################
# --- Agente 3: Buscador e Validador de Fontes --- #
####################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
async def agente_busca_valida_fontes(query, fontes_confiaveis=None):
    """
    Agente responsável por buscar informações relevantes para uma consulta
    e validar a credibilidade das fontes (usando google-adk).
    ...
    """

    instruction = f"""
    Sua função é buscar informações relevantes para a seguinte consulta: "{query}".
    Você DEVE usar a ferramenta ('Google Search') para realizar esta busca.
    Priorize a busca em fontes confiáveis, se uma lista de fontes confiáveis for fornecida.

    Ao realizar a busca, siga os seguintes passos:
    1. Utilize a ferramenta ('Google Search') para encontrar informações relevantes sobre "{query}".
    2. Avalie a credibilidade das fontes encontradas. Se uma lista de 'fontes_confiaveis' for fornecida ({fontes_confiaveis if fontes_confiaveis else "Nenhuma lista fornecida"}),
       priorize e destaque as informações provenientes dessas fontes.
    3. Se a ferramenta ('Google Search') fornecer informações sobre as páginas utilizadas (metadados dos resultados), inclua essas informações na sua resposta.
    4. Formate sua resposta de forma clara, indicando as informações encontradas e as fontes de onde elas vieram,
       mencionando se a fonte é considerada confiável (com base na lista fornecida, se houver).
    5. Se não encontrar informações relevantes em fontes confiáveis (ou em nenhuma fonte), informe isso de forma clara.

    Consulta: "{query}"
    """
    # A lista de fontes confiáveis já está na instrução, o modelo deve considerá-la.

    busca_agente = Agent(
        name="agente_busca_valida_fontes",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para buscar e validar informações em fontes confiáveis.",
        tools=[google_search_tool_instance]  # <--- USE a instância da ferramenta importada
    )

    # A entrada para o agente não precisa repetir as fontes confiáveis se já estão na instrução.
    # O modelo usará a ferramenta Google Search com a query fornecida.
    entrada_do_agente = f"Por favor, busque informações sobre: {query}"

    # Use await aqui, pois call_agent é assíncrono
    resposta_do_agente = await call_agent(busca_agente, entrada_do_agente)
    return resposta_do_agente

# %%
#################################################
# --- Agente 4: Contexto e Memória de Sessão --- #
#################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
async def agente_contexto(historico_conversa=None):
    """
    Agente responsável por manter e fornecer o contexto da conversa (usando google-adk).
    ...
    """
    historico_str = "Nenhum histórico disponível."
    if historico_conversa:
        # Formatar o histórico de forma mais legível para o modelo
        linhas_historico = []
        for item in historico_conversa:
            # Garante que 'role' e 'content' existam e sejam strings antes de formatar
            role = str(item.get('role', 'desconhecido')).capitalize()
            content = str(item.get('content', ''))
            linhas_historico.append(f"{role}: {content}")
        historico_str = "\n".join(linhas_historico)

    instruction = f"""
    Sua função é analisar o seguinte histórico da conversa e, se necessário, resumi-lo ou
    apresentá-lo de forma clara para ser usado como contexto por outros agentes.
    O objetivo é que outros agentes possam entender o fluxo da interação
    e evitar repetições ou informações desconexas.

    Formate o histórico de forma concisa e cronológica.
    Inclua o papel do participante ('Usuário' ou 'Agente') e o conteúdo da mensagem.

    Histórico da conversa fornecido:
    {historico_str}

    Apresente este histórico de forma organizada. Se o histórico for muito longo,
    forneça um resumo conciso dos principais pontos e das últimas interações.
    """

    # Não é necessário redefinir Agent e call_agent aqui.
    # Elas são importadas globalmente.

    contexto_agente = Agent( # Usa a classe Agent global
        name="agente_contexto",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para gerenciar e fornecer o contexto da conversa."
    )

    # A entrada pode ser simplesmente uma solicitação para processar o histórico já na instrução.
    # Ou, se preferir, passar o histórico aqui também.
    entrada_do_agente = f"Analisar e formatar o seguinte histórico: {historico_str}"

    # Use await aqui, pois call_agent é assíncrono
    contexto_formatado = await call_agent(contexto_agente, entrada_do_agente) # Usa a call_agent global
    return contexto_formatado

# Exemplo de como usar:
# historico_exemplo_contexto = [
#     {"role": "usuário", "content": "Qual a capital da França?"},
#     {"role": "agente", "content": "A capital da França é Paris."},
#     {"role": "usuário", "content": "Qual a população de Paris?"}
# ]
# # Use await para chamar a função no exemplo, se executá-lo
# # contexto_processado = await agente_contexto(historico_exemplo_contexto)
# # print(f"--- Contexto Processado pelo Agente ---\n{contexto_processado}")

# %%
######################################################
# --- Agente 5: Curadoria e Sugestão de Conteúdo --- #
######################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
# CORREÇÃO: Remova 'tool' da lista de parâmetros se ele estiver aqui
async def agente_curadoria_conteudo(topico, nivel_estudante=None, historico_conversa=None, fontes_confiaveis=None):
    """
    Agente responsável por curar e sugerir conteúdo educacional relevante
    com base no tópico, nível do estudante e histórico da conversa (usando google-adk).

    Args:
        topico (str): O tópico principal de estudo.
        nivel_estudante (str, optional): O nível de escolaridade do estudante
            (e.g., "fundamental", "médio"). Defaults to None.
        historico_conversa (str, optional): Histórico formatado da conversa.
            Defaults to None.
        fontes_confiaveis (list, optional): Lista de URLs ou padrões de URLs
            considerados fontes confiáveis. Defaults to None.
        # Removido Google Search_tool, pois a ferramenta é passada no Agent
        # Verifique se 'tool' NÃO está listado aqui como um parâmetro obrigatório ou opcional.

    Returns:
        str: Uma sugestão de conteúdo educacional relevante para o estudante.
    """

    instruction = f"""
    Sua função é curar e sugerir conteúdo educacional relevante para o tópico: "{topico}".
    Considere o nível do estudante (se fornecido) e o histórico da conversa para fazer sugestões personalizadas.
    Priorize a sugestão de conteúdo de fontes confiáveis, se uma lista for fornecida.

    Ao fazer sugestões, você deve:
    1. Utilize a ferramenta google ('Google Search') para encontrar recursos educacionais relevantes para o tópico (artigos, vídeos, exercícios, etc.). Use a consulta: "{topico} material de estudo {nivel_estudante if nivel_estudante else ''}"
    2. Se o nível do estudante for fornecido ("fundamental" ou "médio"), adapte as sugestões para serem apropriadas.
    3. Analisar o histórico da conversa para identificar lacunas no conhecimento ou áreas de interesse do estudante
       e sugerir conteúdo que possa aprofundar o aprendizado ou explorar esses interesses.
    4. Priorizar o conteúdo de fontes confiáveis, mencionando a fonte na sua sugestão.
    5. Formate sua sugestão de forma clara e concisa, incluindo um breve resumo do conteúdo sugerido e um link (se disponível).
    6. Se não encontrar conteúdo relevante ou adequado, informe isso de forma clara e sugira outras abordagens (e.g., refinar a busca).

    Tópico: "{topico}"
    {f"Nível do estudante: {nivel_estudante}" if nivel_estudante else ""}
    {f"Histórico da conversa: {historico_conversa}" if historico_conversa else ""}
    {f"Fontes confiáveis a considerar: {fontes_confiaveis}" if fontes_confiaveis else ""}
# %%
######################################################
# --- Agente 5: Curadoria e Sugestão de Conteúdo --- #
######################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
# CORREÇÃO: Remova 'tool' da lista de parâmetros se ele estiver aqui
# %%
######################################################
# --- Agente 5: Curadoria e Sugestão de Conteúdo --- #
######################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
# CORREÇÃO: Remova 'tool' da lista de parâmetros se ele estiver aqui
# %%
######################################################
# --- Agente 5: Curadoria e Sugestão de Conteúdo --- #
######################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
# CORREÇÃO: Remova 'tool' da lista de parâmetros se ele estiver aqui
async def agente_curadoria_conteudo(topico, nivel_estudante=None, historico_conversa=None, fontes_confiaveis=None):
    """
    Agente responsável por curar e sugerir conteúdo educacional relevante
    com base no tópico, nível do estudante e histórico da conversa (usando google-adk).

    Args:
        topico (str): O tópico principal de estudo.
        nivel_estudante (str, optional): O nível de escolaridade do estudante
            (e.g., "fundamental", "médio"). Defaults to None.
        historico_conversa (str, optional): Histórico formatado da conversa.
            Defaults to None.
        fontes_confiaveis (list, optional): Lista de URLs ou padrões de URLs
            considerados fontes confiáveis. Defaults to None.
        # Removido Google Search_tool, pois a ferramenta é passada no Agent
        # Verifique se 'tool' NÃO está listado aqui como um parâmetro obrigatório ou opcional.

    Returns:
        str: Uma sugestão de conteúdo educacional relevante para o estudante.
    """

    instruction = f"""
    Sua função é curar e sugerir conteúdo educacional relevante para o tópico: "{topico}".
    Considere o nível do estudante (se fornecido) e o histórico da conversa para fazer sugestões personalizadas.
    Priorize a sugestão de conteúdo de fontes confiáveis, se uma lista for fornecida.

    Ao fazer sugestões, você deve:
    1. Utilize a ferramenta google ('Google Search') para encontrar recursos educacionais relevantes para o tópico (artigos, vídeos, exercícios, etc.). Use a consulta: "{topico} material de estudo {nivel_estudante if nivel_estudante else ''}"
    2. Se o nível do estudante for fornecido ("fundamental" ou "médio"), adapte as sugestões para serem apropriadas.
    3. Analisar o histórico da conversa para identificar lacunas no conhecimento ou áreas de interesse do estudante
       e sugerir conteúdo que possa aprofundar o aprendizado ou explorar esses interesses.
    4. Priorizar o conteúdo de fontes confiáveis, mencionando a fonte na sua sugestão.
    5. Formate sua sugestão de forma clara e concisa, incluindo um breve resumo do conteúdo sugerido e um link (se disponível).
    6. Se não encontrar conteúdo relevante ou adequado, informe isso de forma clara e sugira outras abordagens (e.g., refinar a busca).

    Tópico: "{topico}"
    {f"Nível do estudante: {nivel_estudante}" if nivel_estudante else ""}
    {f"Histórico da conversa: {historico_conversa}" if historico_conversa else ""}
    {f"Fontes confiáveis a considerar: {fontes_confiaveis}" if fontes_confiaveis else ""}
    """
    # Passe a ferramenta Google Search_tool_instance para o agente
    tools_list = [Google_Search_tool_instance] # Use a instância importada


    curadoria_agente = Agent(
        name="agente_curadoria_conteudo",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para curar e sugerir conteúdo educacional relevante.",
        tools=tools_list # <--- USE a variável tools_list aqui
    )

    # A entrada para o agente é apenas o tópico e o contexto relevante, não a consulta de pesquisa em si.
    # A instrução do agente o guia para formular a consulta de pesquisa usando a ferramenta.
    entrada_do_agente = f"Tópico: {topico}"
    if nivel_estudante:
        entrada_do_agente += f"\nNível do estudante: {nivel_estudante}"
    if historico_conversa:
        entrada_do_agente += f"\nHistórico: {historico_conversa}"
    if fontes_confiaveis:
        entrada_do_agente += f"\nFontes confiáveis: {fontes_confiaveis}"


    # Use await aqui, pois call_agent é assíncrono
    resposta_do_agente = await call_agent(curadoria_agente, entrada_do_agente)
    return resposta_do_agente
    Args:
        topico (str): O tópico principal de estudo.
        nivel_estudante (str, optional): O nível de escolaridade do estudante
            (e.g., "fundamental", "médio"). Defaults to None.
        historico_conversa (str, optional): Histórico formatado da conversa.
            Defaults to None.
        fontes_confiaveis (list, optional): Lista de URLs ou padrões de URLs
            considerados fontes confiáveis. Defaults to None.
        # Removido Google Search_tool, pois a ferramenta é passada no Agent
        # Verifique se 'tool' NÃO está listado aqui como um parâmetro obrigatório ou opcional.

    Returns:
        str: Uma sugestão de conteúdo educacional relevante para o estudante.
    """

    instruction = f"""
    Sua função é curar e sugerir conteúdo educacional relevante para o tópico: "{topico}".
    Considere o nível do estudante (se fornecido) e o histórico da conversa para fazer sugestões personalizadas.
    Priorize a sugestão de conteúdo de fontes confiáveis, se uma lista for fornecida.

    Ao fazer sugestões, você deve:
    1. Utilize a ferramenta google ('Google Search') para encontrar recursos educacionais relevantes para o tópico (artigos, vídeos, exercícios, etc.). Use a consulta: "{topico} material de estudo {nivel_estudante if nivel_estudante else ''}"
    2. Se o nível do estudante for fornecido ("fundamental" ou "médio"), adapte as sugestões para serem apropriadas.
    3. Analisar o histórico da conversa para identificar lacunas no conhecimento ou áreas de interesse do estudante
       e sugerir conteúdo que possa aprofundar o aprendizado ou explorar esses interesses.
    4. Priorizar o conteúdo de fontes confiáveis, mencionando a fonte na sua sugestão.
    5. Formate sua sugestão de forma clara e concisa, incluindo um breve resumo do conteúdo sugerido e um link (se disponível).
    6. Se não encontrar conteúdo relevante ou adequado, informe isso de forma clara e sugira outras abordagens (e.g., refinar a busca).

    Tópico: "{topico}"
    {f"Nível do estudante: {nivel_estudante}" if nivel_estudante else ""}
    {f"Histórico da conversa: {historico_conversa}" if historico_conversa else ""}
    {f"Fontes confiáveis a considerar: {fontes_confiaveis}" if fontes_confiaveis else ""}
    """
    # Passe a ferramenta Google Search_tool_instance para o agente
    tools_list = [Google_Search_tool_instance] # Use a instância importada


    curadoria_agente = Agent(
        name="agente_curadoria_conteudo",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para curar e sugerir conteúdo educacional relevante.",
        tools=tools_list # <--- USE a variável tools_list aqui
    )

    # A entrada para o agente é apenas o tópico e o contexto relevante, não a consulta de pesquisa em si.
    # A instrução do agente o guia para formular a consulta de pesquisa usando a ferramenta.
    entrada_do_agente = f"Tópico: {topico}"
    if nivel_estudante:
        entrada_do_agente += f"\nNível do estudante: {nivel_estudante}"
    if historico_conversa:
        entrada_do_agente += f"\nHistórico: {historico_conversa}"
    if fontes_confiaveis:
        entrada_do_agente += f"\nFontes confiáveis: {fontes_confiaveis}"


    # Use await aqui, pois call_agent é assíncrono
    resposta_do_agente = await call_agent(curadoria_agente, entrada_do_agente)
    return resposta_do_agente
    Args:
        topico (str): O tópico principal de estudo.
        nivel_estudante (str, optional): O nível de escolaridade do estudante
            (e.g., "fundamental", "médio"). Defaults to None.
        historico_conversa (str, optional): Histórico formatado da conversa.
            Defaults to None.
        fontes_confiaveis (list, optional): Lista de URLs ou padrões de URLs
            considerados fontes confiáveis. Defaults to None.
        # Removido Google Search_tool, pois a ferramenta é passada no Agent
        # Verifique se 'tool' NÃO está listado aqui como um parâmetro obrigatório ou opcional.

    Returns:
        str: Uma sugestão de conteúdo educacional relevante para o estudante.
    """

    instruction = f"""
    Sua função é curar e sugerir conteúdo educacional relevante para o tópico: "{topico}".
    Considere o nível do estudante (se fornecido) e o histórico da conversa para fazer sugestões personalizadas.
    Priorize a sugestão de conteúdo de fontes confiáveis, se uma lista for fornecida.

    Ao fazer sugestões, você deve:
    1. Utilize a ferramenta google ('Google Search') para encontrar recursos educacionais relevantes para o tópico (artigos, vídeos, exercícios, etc.). Use a consulta: "{topico} material de estudo {nivel_estudante if nivel_estudante else ''}"
    2. Se o nível do estudante for fornecido ("fundamental" ou "médio"), adapte as sugestões para serem apropriadas.
    3. Analisar o histórico da conversa para identificar lacunas no conhecimento ou áreas de interesse do estudante
       e sugerir conteúdo que possa aprofundar o aprendizado ou explorar esses interesses.
    4. Priorizar o conteúdo de fontes confiáveis, mencionando a fonte na sua sugestão.
    5. Formate sua sugestão de forma clara e concisa, incluindo um breve resumo do conteúdo sugerido e um link (se disponível).
    6. Se não encontrar conteúdo relevante ou adequado, informe isso de forma clara e sugira outras abordagens (e.g., refinar a busca).

    Tópico: "{topico}"
    {f"Nível do estudante: {nivel_estudante}" if nivel_estudante else ""}
# %%
######################################################
# --- Agente 5: Curadoria e Sugestão de Conteúdo --- #
######################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
# CORREÇÃO: Remova 'tool' da lista de parâmetros se ele estiver aqui
async def agente_curadoria_conteudo(topico, nivel_estudante=None, historico_conversa=None, fontes_confiaveis=None):
    """
    Agente responsável por curar e sugerir conteúdo educacional relevante
    com base no tópico, nível do estudante e histórico da conversa (usando google-adk).

    Args:
        topico (str): O tópico principal de estudo.
        nivel_estudante (str, optional): O nível de escolaridade do estudante
            (e.g., "fundamental", "médio"). Defaults to None.
        historico_conversa (str, optional): Histórico formatado da conversa.
            Defaults to None.
        fontes_confiaveis (list, optional): Lista de URLs ou padrões de URLs
            considerados fontes confiáveis. Defaults to None.
        # Removido Google Search_tool, pois a ferramenta é passada no Agent
        # Verifique se 'tool' NÃO está listado aqui como um parâmetro obrigatório ou opcional.

    Returns:
        str: Uma sugestão de conteúdo educacional relevante para o estudante.
    """

    instruction = f"""
    Sua função é curar e sugerir conteúdo educacional relevante para o tópico: "{topico}".
    Considere o nível do estudante (se fornecido) e o histórico da conversa para fazer sugestões personalizadas.
    Priorize a sugestão de conteúdo de fontes confiáveis, se uma lista for fornecida.

    Ao fazer sugestões, você deve:
    1. Utilize a ferramenta google ('Google Search') para encontrar recursos educacionais relevantes para o tópico (artigos, vídeos, exercícios, etc.). Use a consulta: "{topico} material de estudo {nivel_estudante if nivel_estudante else ''}"
    2. Se o nível do estudante for fornecido ("fundamental" ou "médio"), adapte as sugestões para serem apropriadas.
    3. Analisar o histórico da conversa para identificar lacunas no conhecimento ou áreas de interesse do estudante
       e sugerir conteúdo que possa aprofundar o aprendizado ou explorar esses interesses.
    4. Priorizar o conteúdo de fontes confiáveis, mencionando a fonte na sua sugestão.
    5. Formate sua sugestão de forma clara e concisa, incluindo um breve resumo do conteúdo sugerido e um link (se disponível).
    6. Se não encontrar conteúdo relevante ou adequado, informe isso de forma clara e sugira outras abordagens (e.g., refinar a busca).

    Tópico: "{topico}"
    {f"Nível do estudante: {nivel_estudante}" if nivel_estudante else ""}
# %%
######################################################
# --- Agente 5: Curadoria e Sugestão de Conteúdo --- #
######################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
# CORREÇÃO: Remova 'tool' da lista de parâmetros se ele estiver aqui
async def agente_curadoria_conteudo(topico, nivel_estudante=None, historico_conversa=None, fontes_confiaveis=None):
    """
    Agente responsável por curar e sugerir conteúdo educacional relevante
    com base no tópico, nível do estudante e histórico da conversa (usando google-adk).

    Args:
        topico (str): O tópico principal de estudo.
        nivel_estudante (str, optional): O nível de escolaridade do estudante
            (e.g., "fundamental", "médio"). Defaults to None.
        historico_conversa (str, optional): Histórico formatado da conversa.
            Defaults to None.
        fontes_confiaveis (list, optional): Lista de URLs ou padrões de URLs
            considerados fontes confiáveis. Defaults to None.
        # Removido Google Search_tool, pois a ferramenta é passada no Agent
        # Verifique se 'tool' NÃO está listado aqui como um parâmetro obrigatório ou opcional.

    Returns:
        str: Uma sugestão de conteúdo educacional relevante para o estudante.

    instruction = f"""
    Sua função é curar e sugerir conteúdo educacional relevante para o tópico: "{topico}".
    Considere o nível do estudante (se fornecido) e o histórico da conversa para fazer sugestões personalizadas.
    Priorize a sugestão de conteúdo de fontes confiáveis, se uma lista for fornecida.

    Ao fazer sugestões, você deve:
    1. Utilize a ferramenta google ('Google Search') para encontrar recursos educacionais relevantes para o tópico (artigos, vídeos, exercícios, etc.). Use a consulta: "{topico} material de estudo {nivel_estudante if nivel_estudante else ''}"
    2. Se o nível do estudante for fornecido ("fundamental" ou "médio"), adapte as sugestões para serem apropriadas.
    3. Analisar o histórico da conversa para identificar lacunas no conhecimento ou áreas de interesse do estudante
       e sugerir conteúdo que possa aprofundar o aprendizado ou explorar esses interesses.
    4. Priorizar o conteúdo de fontes confiáveis, mencionando a fonte na sua sugestão.
    5. Formate sua sugestão de forma clara e concisa, incluindo um breve resumo do conteúdo sugerido e um link (se disponível).
    6. Se não encontrar conteúdo relevante ou adequado, informe isso de forma clara e sugira outras abordagens (e.g., refinar a busca).

    Tópico: "{topico}"
    {f"Nível do estudante: {nivel_estudante}" if nivel_estudante else ""}
    {f"Histórico da conversa: {historico_conversa}" if historico_conversa else ""}
    {f"Fontes confiáveis a considerar: {fontes_confiaveis}" if fontes_confiaveis else ""}
    """
    # Passe a ferramenta Google Search_tool_instance para o agente
    tools_list = [Google_Search_tool_instance] # Use a instância importada


    curadoria_agente = Agent(
        name="agente_curadoria_conteudo",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para curar e sugerir conteúdo educacional relevante.",
        tools=tools_list # <--- USE a variável tools_list aqui
    )

    # A entrada para o agente é apenas o tópico e o contexto relevante, não a consulta de pesquisa em si.
    # A instrução do agente o guia para formular a consulta de pesquisa usando a ferramenta.
    entrada_do_agente = f"Tópico: {topico}"
    if nivel_estudante:
        entrada_do_agente += f"\nNível do estudante: {nivel_estudante}"
    if historico_conversa:
        entrada_do_agente += f"\nHistórico: {historico_conversa}"
    if fontes_confiaveis:
        entrada_do_agente += f"\nFontes confiáveis: {fontes_confiaveis}"


    # Use await aqui, pois call_agent é assíncrono
    resposta_do_agente = await call_agent(curadoria_agente, entrada_do_agente)
    return resposta_do_agente


    curadoria_agente = Agent(
        name="agente_curadoria_conteudo",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para curar e sugerir conteúdo educacional relevante.",
        tools=tools_list # <--- USE a variável tools_list aqui
    )

    # A entrada para o agente é apenas o tópico e o contexto relevante, não a consulta de pesquisa em si.
    # A instrução do agente o guia para formular a consulta de pesquisa usando a ferramenta.
    entrada_do_agente = f"Tópico: {topico}"
    if nivel_estudante:
        entrada_do_agente += f"\nNível do estudante: {nivel_estudante}"
    if historico_conversa:
        entrada_do_agente += f"\nHistórico: {historico_conversa}"
    if fontes_confiaveis:
        entrada_do_agente += f"\nFontes confiáveis: {fontes_confiaveis}"


    # Use await aqui, pois call_agent é assíncrono
    resposta_do_agente = await call_agent(curadoria_agente, entrada_do_agente)
    return resposta_do_agente


    curadoria_agente = Agent(
        name="agente_curadoria_conteudo",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para curar e sugerir conteúdo educacional relevante.",
        tools=tools_list # <--- USE a variável tools_list aqui
    )

    # A entrada para o agente é apenas o tópico e o contexto relevante, não a consulta de pesquisa em si.
    # A instrução do agente o guia para formular a consulta de pesquisa usando a ferramenta.
    entrada_do_agente = f"Tópico: {topico}"
    if nivel_estudante:
        entrada_do_agente += f"\nNível do estudante: {nivel_estudante}"
    if historico_conversa:
        entrada_do_agente += f"\nHistórico: {historico_conversa}"
    if fontes_confiaveis:
        entrada_do_agente += f"\nFontes confiáveis: {fontes_confiaveis}"


    # Use await aqui, pois call_agent é assíncrono
    resposta_do_agente = await call_agent(curadoria_agente, entrada_do_agente)
    return resposta_do_agente
    curadoria_agente = Agent(
        name="agente_curadoria_conteudo",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para curar e sugerir conteúdo educacional relevante.",
        tools=tools_list # <--- USE a variável tools_list aqui
    )

    # A entrada para o agente é apenas o tópico e o contexto relevante, não a consulta de pesquisa em si.
    # A instrução do agente o guia para formular a consulta de pesquisa usando a ferramenta.
    entrada_do_agente = f"Tópico: {topico}"
    if nivel_estudante:
        entrada_do_agente += f"\nNível do estudante: {nivel_estudante}"
    if historico_conversa:
        entrada_do_agente += f"\nHistórico: {historico_conversa}"
    if fontes_confiaveis:
        entrada_do_agente += f"\nFontes confiáveis: {fontes_confiaveis}"


    # Use await aqui, pois call_agent é assíncrono
    resposta_do_agente = await call_agent(curadoria_agente, entrada_do_agente)
    return resposta_do_agente

# %%
########################################################
# --- Agente 6: Apresentação e Formatação de Texto --- #
########################################################

# Tornar esta função assíncrona, pois ela chama await call_agent
async def agente_apresentacao(conteudo, formato="markdown", **kwargs):
    """
    Agente responsável por formatar e apresentar o conteúdo para o usuário (usando google-adk).

    Args:
        conteudo (str): O texto ou conteúdo a ser apresentado.
        formato (str, optional): O formato de apresentação ('markdown' ou 'html').
            Defaults to "markdown".
        **kwargs: Argumentos adicionais que podem ser usados para formatação
            específica (e.g., cores, estilos).
    """

    instruction = f"""
    Sua função é formatar e apresentar o seguinte conteúdo para o usuário
    de forma clara, organizada e visualmente agradável.

    Conteúdo a ser apresentado:
    "{conteudo}"

    Formato de apresentação solicitado: "{formato}"

    Instruções de formatação adicionais (se fornecidas):
    "{kwargs if kwargs else 'Nenhuma instrução adicional.'}"

    Dependendo do formato solicitado, utilize as ferramentas e técnicas apropriadas
    para melhorar a legibilidade e o impacto do conteúdo.

    Para 'markdown': utilize a sintaxe Markdown para negrito, itálico, listas, cabeçalhos, etc.
    Para 'html': utilize tags HTML para estruturar e estilizar o conteúdo (cores, divs, spans, etc.).
    Considere a largura da tela para evitar quebras de linha inadequadas (use 'textwrap' se necessário).
    Se houver informações importantes (como fontes confiáveis), destaque-as.
    """

    apresentacao_agente = Agent(
        name="agente_apresentacao",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para formatar e apresentar conteúdo ao usuário."
    )

    # A entrada para o agente é apenas o conteúdo, formato e argumentos adicionais.
    entrada_do_agente = f"Conteúdo: {conteudo}\nFormato: {formato}\nArgumentos: {kwargs}"

    # A saída deste agente será o próprio conteúdo formatado (espera-se).
    # Use await aqui, pois call_agent é assíncrono
    conteudo_formatado = await call_agent(apresentacao_agente, entrada_do_agente)


    # Para garantir a formatação visual no notebook, usamos IPython.display aqui.
    # O agente formatou o *texto*, agora exibimos o texto formatado.
    if formato.lower() == "markdown":
        display(Markdown(conteudo_formatado))
    elif formato.lower() == "html":
        display(HTML(conteudo_formatado))
    else:
        print(conteudo_formatado) # Exibe como texto plano se o formato não for reconhecido

    # Retornamos o conteúdo formatado para possível uso em outros lugares
    return conteudo_formatado

# %%
##########################################
# --- Agente 7: Feedback e Adaptação --- #
##########################################
# Tornar esta função assíncrona, pois ela chama await call_agent
async def agente_feedback_adaptacao(ultima_pergunta, resposta_estudante, historico_conversa=None):
    """
    Agente responsável por analisar a resposta do estudante e o histórico da conversa
    para fornecer feedback e adaptar a estratégia de aprendizado (usando google-adk).

    Args:
        ultima_pergunta (str): A última pergunta feita ao estudante.
        resposta_estudante (str): A resposta fornecida pelo estudante.
        historico_conversa (str, optional): Histórico formatado da conversa.
            Defaults to None.

    Returns:
        str: Uma mensagem de feedback para o estudante e/ou uma sugestão de adaptação
             para o agente de questionamento.
    """

    instruction = f"""
    Sua função é analisar a resposta do estudante à última pergunta e o histórico da conversa
    para fornecer feedback construtivo e sugerir adaptações na estratégia de aprendizado.

    Última pergunta: "{ultima_pergunta}"
    Resposta do estudante: "{resposta_estudante}"

    Histórico da conversa:
    "{historico_conversa if historico_conversa else 'Nenhum histórico disponível.'}"

    Ao analisar a resposta, você deve considerar:
    - A correção da resposta (se possível determinar com base no seu conhecimento).
    - O nível de compreensão demonstrado pelo estudante.
    - Quaisquer lacunas no conhecimento ou áreas de confusão aparentes.
    - O engajamento e o nível de participação do estudante.

    Com base na sua análise, você deve:
    1. Fornecer feedback claro e encorajador ao estudante, destacando os pontos positivos
       e oferecendo sugestões para melhoria, se necessário.
    2. Sugerir adaptações para o agente de questionamento, como:
       - Simplificar as próximas perguntas se o estudante estiver com dificuldades.
       - Oferecer mais exemplos ou analogias.
       - Aprofundar a discussão se o estudante demonstrar boa compreensão.
       - Mudar o tópico se o estudante parecer desinteressado ou frustrado.
    3. Seja específico em suas sugestões de adaptação, indicando claramente o que o
       agente de questionamento deve fazer.

    Sua saída deve ser uma mensagem para o estudante (feedback) e/ou uma mensagem
    direcionada ao agente de questionamento (sugestão de adaptação), separadas claramente.
    """

    feedback_adaptacao_agente = Agent(
        name="agente_feedback_adaptacao",
        model=MODEL_ID, # Usar a variável global MODEL_ID
        instruction=instruction,
        description="Agente para fornecer feedback e adaptar a estratégia de aprendizado."
    )

    entrada_do_agente = f"Última pergunta: {ultima_pergunta}\nResposta: {resposta_estudante}\nHistórico: {historico_conversa if historico_conversa else 'Nenhum histórico.'}"

    # A saída deste agente será o feedback para o estudante e/ou a sugestão para o questionador (espera-se).
    # Use await aqui, pois call_agent é assíncrono
    retorno_do_agente = await call_agent(feedback_adaptacao_agente, entrada_do_agente)
    return retorno_do_agente

# %%
####################################################
# --- Agente 8: Anexador de Fontes Interativas --- #
####################################################

# Esta função não precisa ser assíncrona, pois não usa await
def agente_anexador_fontes_parser_direto(comando_usuario, lista_fontes_atual=None):
    if lista_fontes_atual is None:
        lista_fontes_atual = []

    mensagem = ""
    comando_lower = comando_usuario.lower().strip()

    if comando_lower.startswith("/adicionar_fonte "):
        try:
            # Usar split(maxsplit=1) para garantir que apenas o primeiro espaço seja usado como separador
            partes = comando_usuario.split(" ", maxsplit=1)
            if len(partes) < 2:
                 raise IndexError # Força o erro de comando inválido se não houver URL

            fonte = partes[1].strip()

            if not fonte: # Verifica se a URL não está vazia
                raise ValueError("URL da fonte não pode ser vazia.")

            # Validação de URL mais robusta pode ser considerada
            # Regex para validar URLs http/https
            url_regex = re.compile(
                r'^(?:http|https)://' # Protocolo (http ou https)
                r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|' # Domínio
                r'localhost|' # ou localhost
                r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ou endereço IP
                r'(?::\d+)?' # Porta opcional
                r'(?:/?|[/?]\S+)$', re.IGNORECASE) # Caminho e query string

            # Se a URL não começar com http ou https, tentar adicionar https:// para validar
            fonte_a_validar = fonte
            if not fonte_a_validar.startswith("http://") and not fonte_a_validar.startswith("https://"):
                 fonte_a_validar = "https://" + fonte_a_validar

            # Verificar se a URL (com ou sem https adicionado para teste) corresponde à regex
            if url_regex.match(fonte_a_validar):
                 # Se a URL original não tinha protocolo, armazenar com https://
                 if not fonte.startswith("http://") and not fonte.startswith("https://"):
                     fonte_final = "https://" + fonte
                 else:
                     fonte_final = fonte # Usar a URL original se já tinha protocolo

                 if fonte_final not in lista_fontes_atual:
                     lista_fontes_atual.append(fonte_final)
                     mensagem = f"✅ Fonte '{fonte_final}' adicionada à lista."
                 else:
                     mensagem = f"ℹ️ A fonte '{fonte_final}' já está na lista."
            else:
                # Se a validação falhou mesmo com https adicionado para teste
                mensagem = f"❌ URL inválida: '{fonte}'. Use o formato correto (e.g., https://www.exemplo.com)."
        except IndexError: # Caso não haja nada após "/adicionar_fonte "
            mensagem = "❌ Comando inválido. Use: /adicionar_fonte <URL>"
        except ValueError as e:
            mensagem = f"❌ Erro: {e}"
        except Exception as e: # Capturar outros erros inesperados durante o processamento
            mensagem = f"❌ Ocorreu um erro inesperado: {e}"


    elif comando_lower.startswith("/remover_fonte "):
        try:
             # Usar split(maxsplit=1) para garantir que apenas o primeiro espaço seja usado como separador
            partes = comando_usuario.split(" ", maxsplit=1)
            if len(partes) < 2:
                 raise IndexError # Força o erro de comando inválido se não houver URL

            fonte = partes[1].strip()

            if not fonte:
                 raise ValueError("URL da fonte não pode ser vazia.")

            # Adicionar "https://" se ausente, para consistência com a adição e remoção
            if not fonte.startswith("http://") and not fonte.startswith("https://"):
                fonte_com_protocolo = "https://" + fonte
                fonte_sem_protocolo = fonte # Guardar original para mensagem de erro
            else:
                fonte_com_protocolo = fonte
                fonte_sem_protocolo = fonte

            removido = False
            # Tenta remover a versão com protocolo primeiro
            if fonte_com_protocolo in lista_fontes_atual:
                lista_fontes_atual.remove(fonte_com_protocolo)
                mensagem = f"🗑️ Fonte '{fonte_com_protocolo}' removida da lista."
                removido = True
            # Se não encontrou com protocolo, tenta remover a versão sem protocolo
            elif fonte_sem_protocolo in lista_fontes_atual:
                 lista_fontes_atual.remove(fonte_sem_protocolo)
                 mensagem = f"🗑️ Fonte '{fonte_sem_protocolo}' removida da lista."
                 removido = True

            if not removido:
                mensagem = f"⚠️ A fonte '{fonte}' não está na lista."

        except IndexError:
            mensagem = "❌ Comando inválido. Use: /remover_fonte <URL>"
        except ValueError as e:
             mensagem = f"❌ Erro: {e}"
        except Exception as e: # Capturar outros erros inesperados durante o processamento
             mensagem = f"❌ Ocorreu um erro inesperado: {e}"


    elif comando_lower == "/listar_fontes":
        if lista_fontes_atual:
            # Ordenar a lista para uma apresentação consistente
            fontes_ordenadas = sorted(lista_fontes_atual)
            mensagem = "📋 Lista de fontes atuais:\n" + "\n".join(f"- {f}" for f in fontes_ordenadas)
        else:
            mensagem = "📚 A lista de fontes está vazia."
    else:
        mensagem = (f"❓ Comando inválido: '{comando_usuario}'. Use '/adicionar_fonte <URL>', "
                    "'/listar_fontes' ou '/remover_fonte <URL>'.")

    # Esta função não é assíncrona, então retorna os valores diretamente.
    return mensagem, lista_fontes_atual # Corrigido: Retorna lista_fontes_atual, não lista_fontes

# %%
# FLUXO DOS AGENTES

# Importações necessárias (já devem estar na célula de imports principal ou em células separadas)
from IPython.display import Markdown, display
# Garanta que esta importação esteja funcionando no seu ambiente
from google.generativeai import GenerativeModel # Use a classe diretamente
from google.adk.agents import Agent # Para os outros agentes
import asyncio # Importe asyncio
# Importe a instância da ferramenta Google Search se ainda não estiver importada
# from google.adk.tools.search import google_search as google_search_tool_instance # Exemplo de import
# Definição das funções dos agentes (simplificadas para o exemplo, assumindo que retornam strings)
# IMPORTANTE: Na implementação real, estas funções provavelmente usariam call_agent ou
# interagiriam com modelos de forma assíncrona, tornando-as 'awaitable'.
# Estou adicionando 'async' e 'await' onde parece que interações com agentes
# externos ou modelos assíncronos ocorreriam, baseado no contexto do erro.

async def agente_boas_vindas():
    # Simula uma resposta inicial
    return "Olá! Sou seu Chatbot Educacional. Como posso te ajudar hoje?"

def agente_anexador_fontes_parser_direto(comando, lista_fontes):
    # Simula processamento de comando de fontes
    if "/adicionar_fonte" in comando:
        fonte = comando.replace("/adicionar_fonte", "").strip()
        if fonte and fonte not in lista_fontes:
            lista_fontes.append(fonte)
            return f"Fonte '{fonte}' adicionada com sucesso.", lista_fontes
        elif fonte:
            return f"Fonte '{fonte}' já está na lista.", lista_fontes
        else:
            return "Comando /adicionar_fonte requer uma URL ou padrão.", lista_fontes
    elif "/remover_fonte" in comando:
        fonte = comando.replace("/remover_fonte", "").strip()
        if fonte and fonte in lista_fontes:
            lista_fontes.remove(fonte)
            return f"Fonte '{fonte}' removida com sucesso.", lista_fontes
        elif fonte:
            return f"Fonte '{fonte}' não encontrada na lista.", lista_fontes
        else:
            return "Comando /remover_fonte requer uma URL ou padrão.", lista_fontes
    elif "/listar_fontes" in comando:
        if lista_fontes:
            return "Fontes confiáveis configuradas:\n" + "\n".join(lista_fontes), lista_fontes
        else:
            return "Nenhuma fonte confiável configurada.", lista_fontes
    else:
        return "Comando de fonte desconhecido.", lista_fontes

async def agente_apresentacao(mensagem, formato="markdown"):
    # Simula a apresentação da mensagem
    if formato == "markdown":
        display(Markdown(mensagem))
    else:
        print(mensagem)

async def agente_contexto(historico_conversa):
    # Simula a geração de contexto baseado no histórico
    contexto = "Histórico:\n"
    for item in historico_conversa:
        contexto += f"{item['role'].capitalize()}: {item['content']}\n"
    return contexto

async def agente_curadoria_conteudo(topico, nivel_estudante, historico_conversa, fontes_confiaveis, tool):
    # Simula a busca e curadoria de conteúdo.
    # Na realidade, usaria a 'tool' (GoogleSearch) e processaria os resultados.
    return f"Conteúdo sobre '{topico}' para nível '{nivel_estudante}', considerando o histórico e fontes confiáveis."

async def agente_questionador(pergunta_usuario, contexto_conversa):
    # Simula a geração de uma pergunta guia
    return f"Para entender melhor, você poderia me falar mais sobre como '{pergunta_usuario}' se relaciona com...?"

async def agente_feedback_adaptacao(pergunta_agente, resposta_estudante, contexto_conversa):
    # Simula a geração de feedback e adaptação
    return "Ótima resposta! Isso me ajuda a entender melhor. O que você pensa sobre...?"

# Definição da classe GoogleSearch (apenas um placeholder para o exemplo)
class GoogleSearch:
    def __call__(self, query):
        print(f"Simulando busca no Google por: {query}")
        # Na implementação real, faria a chamada à API de busca
        return f"Resultados da busca por '{query}'..."


async def main(): # Função principal assíncrona
    # Inicialização da lista de fontes confiáveis
    lista_fontes_confiaveis = [
        "https://scholar.google.com.br/",
        "https://www.scielo.br/",
        "https://oasisbr.ibict.br/",
        "https://bdtd.ibict.br/",
        "https://educapes.capes.gov.br/",
        "https://www.dominiopublico.gov.br/",
        "https://anais.abc.org.br/",
        "https://sbfisica.org.br/rbef/",
        "https://www.sbm.org.br/boletim/",
        "https://www.scielo.br/boletim/",
        "https://www.scielo.br/rsp/",
        "https://www.scielo.br/csp/",
        "https://www.scielo.br/mioc/",
        "https://www.scielo.br/rbcsoc/",
        "https://www.scielo.br/rbcsoc/",
        "https://www.scielo.br/ccampo/",
        "https://www.scielo.br/nec/",
        "https://rae.fgv.br/",
        "https://www.scielo.br/opiniaop/",
        "https://www.scielo.br/dados/",
        "*.br",
        "*.edu.br",
        "*.gov.br",
        "*.org.br",
        "*.usp.br",
        "*.unicamp.br",
        "*.ufrj.br",
        "*.ufmg.br",
        "*.unesp.br",
        "*.ufrgs.br",
        "*.ita.br",
        "https://periodicos.capes.gov.br/",
        "https://lume.ufrgs.br/",
        "https://catalogodeteses.capes.gov.br/"
    ]

    # Inicialização do histórico da conversa
    historico = []

    # Agente de Boas-Vindas (usando a função definida)
    print("Iniciando o Chatbot Educacional...")
    # Use await aqui, pois a função agente_boas_vindas foi tornada awaitable
    mensagem_inicial = await agente_boas_vindas()
    display(Markdown(mensagem_inicial))


    while True:
        pergunta_usuario = input("Digite sua pergunta ou comando aqui: ")
        if pergunta_usuario.lower() in ["sair", "fim", "adeus"]:
            print("Chatbot: Até a próxima!")
            break

        # 1. Agente de Anexador de Fontes Interativas (tratamento de comandos)
        if pergunta_usuario.lower().startswith(("/adicionar_fonte", "/remover_fonte", "/listar_fontes")):
            mensagem_fonte, lista_fontes_confiaveis = agente_anexador_fontes_parser_direto(pergunta_usuario, lista_fontes_confiaveis)
            await agente_apresentacao(f"Gerenciamento de Fontes:\n{mensagem_fonte}", formato="markdown")
            historico.append({"role": "sistema", "content": f"Comando de fontes: {pergunta_usuario}. Resultado: {mensagem_fonte}"})

        else:
            # --- Fluxo normal do chatbot para perguntas ---
            historico.append({"role": "usuário", "content": pergunta_usuario})


            # 2. Agente de Contexto e Memória
            contexto_atual_formatado = await agente_contexto(historico)


            # 3. Decidir o fluxo: Questionamento Guiado ou Pesquisa Direta/Curadoria
            palavras_chave_pesquisa = ["o que é", "explique", "quem foi", "como funciona", "pesquise sobre", "me fale sobre", "defina"]
            precisa_de_pesquisa_direta = any(keyword in pergunta_usuario.lower() for keyword in palavras_chave_pesquisa)

            if precisa_de_pesquisa_direta:
                display(Markdown("🔍 Consultando meus conhecimentos e buscando informações para você..."))
                sugestao_conteudo = await agente_curadoria_conteudo(
                    topico=pergunta_usuario,
                    nivel_estudante="ensino fundamental ou médio",
                    historico_conversa=contexto_atual_formatado,
                    fontes_confiaveis=lista_fontes_confiaveis
                )
                await agente_apresentacao(f"Aqui estão algumas informações e recursos que encontrei:\n{sugestao_conteudo}", formato="markdown")
                historico.append({"role": "agente", "content": sugestao_conteudo})

            else:
                # 4b. Agente de Questionamento Guiado
                # agente_questionador agora precisa ser awaitable
                pergunta_do_agente_guiado = await agente_questionador(pergunta_usuario, contexto_atual_formatado)
                ultima_pergunta_agente = pergunta_do_agente_guiado # Salva para o feedback
                # agente_apresentacao agora precisa ser awaitable
                await agente_apresentacao(f"Agente Guia: {pergunta_do_agente_guiado}", formato="markdown")
                historico.append({"role": "agente", "content": pergunta_do_agente_guiado})

                # 5. Estudante responde à pergunta do agente guia (input é síncrono, pode ficar aqui)
                resposta_estudante = input("Sua resposta/reflexão: ")
                historico.append({"role": "usuário", "content": resposta_estudante})

                # 6. Agente de Feedback e Adaptação (após resposta ao agente guia)
                contexto_para_feedback = await agente_contexto(historico)
                feedback_e_adaptacao = await agente_feedback_adaptacao(ultima_pergunta_agente, resposta_estudante, contexto_para_feedback)
                await agente_apresentacao(f"Feedback do Guia:\n{feedback_e_adaptacao}", formato="markdown")

        print("\n") # Espaço entre as interações

# Finalmente, execute a função main assíncrona
# Remova asyncio.run()
# asyncio.run(main())

# No ambiente Colab/Jupyter, você pode simplesmente aguardar a função top-level
# Certifique-se de que a célula do notebook suporta awaits de nível superior
# ou execute-o usando get_ipython().run_line_magic('autoawait', 'true') no início
# if __name__ == "__main__": # Isso é para scripts Python, não ideal para notebooks
#     asyncio.run(main())

# Para executar em um notebook/Colab:
await main()

